apiVersion: v1
description: A Helm chart for Nuxeo Web UI
icon: https://media.licdn.com/dms/image/C4D0BAQFPXiXFrp4LBA/company-logo_200_200/0?e=2159024400&v=beta&t=RW9EU0QUciUVuPSpLySd9FtJ2yG-O37_hAAvc32f6ro
name: nuxeo-web-ui
version: 3.0.0-SNAPSHOT
